
#:include widgets/param_slider.kv
#:include widgets/separator.kv
#:include widgets/spacer.kv
#:include widgets/viewer.kv
#:include widgets/histogram.kv
#:include widgets/metainfo.kv
#:include widgets/color_picker.kv
#:include widgets/export_dialog.kv
#:include widgets/hover_spinner.kv
#:include widgets/curve.kv
#:include widgets/mask2_content.kv
#:include widgets/history_content.kv

#:set clear_color 0, 0, 0, 0
#:set dark_color 0.08, 0.08, 0.08, 1

<DistortionEffectButton@ToggleButton>:
    group: 'effect'
    font_size: '9pt'
    pos_hint: {'center_x': .5, 'center_y': .5}
    ref_height: 20

<ParamChip@MDChip>:
    type: 'filter'
    pos_hint: {"center_x": .5, "center_y": .5}
    size_hint_y: None
    ref_height: 20
    radius: 40
    line_color: 'grey'

<ParamChipText@MDChipText>:
    font_size: '9pt'
    color: 'b0b0b0' 

<MainSpinnerOption@SpinnerOption>:
    size_hint_y: None
    height: dp(20)

<ParamSpinner@HoverSpinner>:
    pos_hint: {'center_x': .5, 'center_y': .5}
    size_hint: 0.55, None
    ref_height: 20
    font_size: '9pt'
    #option_cls: "MainSpinnerOption"

<IconTabbedPanelItem@TabbedPanelItem>:
    icon_source: ''
    text: ''
    canvas.after:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.center_x - (self.height * 0.7) / 2, self.center_y - (self.height * 0.7) / 2
            size: self.height * 0.7, self.height * 0.7
            source: root.icon_source

<CurveTabbedPanel@TabbedPanel>:
    size_hint: None, None
    width: self.parent.width
    height: self.parent.width
    ref_tab_width: 80
    ref_tab_height: 20
    do_default_tab: False
    on_kv_post: self.switch_to(root.tab_list[0]) if root.tab_list else None

<SelectableListItem@OneLineListItem>:
    on_release: app.item_selected(self.text)

<MainWidget>:
    loading: True

    BoxLayout:
        orientation: 'vertical'
        size: root.size

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, None
            ref_height: 30

            HSpacer:
                size_hint_x: 0.9
            Button:
                size_hint_x: None
                ref_width: 60
                ref_height: 15
                font_size: '9pt'
                text: "Reset"
                on_press: root.on_reset_press()
            ToggleButton:
                id: preset
                size_hint_x: None
                ref_width: 60
                ref_height: 15
                font_size: '9pt'
                text: "Preset"
                #on_state: root.on_preset_press(self.state)

        BoxLayout:
            orientation: 'horizontal'

            BoxLayout:
                id: info
                orientation: 'vertical'
                size_hint: 0.3, 1
                ref_margin: 8
                ref_spacing: 8

                HistogramWidget:
                    id: histogram
                    size_hint: None, None
                    ref_width: 256+128
                    ref_height: 128-32
                    ref_margin: 4
                    canvas:
                        Color:
                            rgba: dark_color
                        Rectangle:
                            size: self.size
                            pos: self.pos                    

                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    ref_height: 16
                    ref_margin: 0
                    
                    ToggleButton:
                        id: toggle_underexposure
                        size_hint_x: None
                        ref_width: 50
                        text: "Under"
                        on_state: root.start_draw_image()
                    ToggleButton:
                        id: toggle_overexposure
                        size_hint_x: None
                        ref_width: 50
                        text: "Over"
                        on_state: root.start_draw_image()

                MDScrollView:
                    size_hint: 1, 0.8

                    BoxLayout:
                        size_hint_y: None
                        orientation: "vertical"
                        height: self.minimum_height

                        MetaInfo:
                            id: exif_file_name
                            key: "File Name"
                        MetaInfo:
                            id: exif_file_size
                            key: "File Size"
                        MetaInfo:
                            id: exif_create_date
                            key: "Create Date"
                        MetaInfo:
                            id: exif_image_size
                            key: "Image Size"
                        MetaInfo:
                            id: exif_iso_speed
                            key: "ISO"
                        MetaInfo:
                            id: exif_aperture
                            key: "Aperture"
                        MetaInfo:
                            id: exif_shutter_speed
                            key: "Shutter Speed"
                        MetaInfo:
                            id: exif_exposure_compensation
                            key: "Exposure Comp."
                        MetaInfo:
                            id: exif_flash
                            key: "Flash"
                        MetaInfo:
                            id: exif_white_balance
                            key: "White Balance"
                        MetaInfo:
                            id: exif_focal_length
                            key: "Focal Length"
                        MetaInfo:
                            id: exif_exposure_program
                            key: "Exposure Program"
                        MetaInfo:
                            id: exif_make
                            key: "Make"
                        MetaInfo:
                            id: exif_model
                            key: "Model"
                        MetaInfo:
                            id: exif_lens_model
                            key: "Lens Model"
                        MetaInfo:
                            id: exif_software
                            key: "Software"
                            
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: 0.7

                FloatLayout:
                    id: preview_widget
                    pos_hint: {'x':0, 'y': 0}
                    size_hint_y: 0.95
                    on_touch_down: root.on_image_touch_down(args[1])
                    on_touch_move: root.on_image_touch_move(args[1])
                    on_touch_up: root.on_image_touch_up(args[1])
               
                    Image:
                        id: preview
                        pos_hint: {'x':0, 'y': 0}
                        canvas:
                            Color:
                                rgba: dark_color if not self.texture else clear_color
                            Rectangle:
                                pos: self.pos
                                size: self.size
 
                    MaskEditor2:
                        id: mask_editor2
                        root: root
                        pos_hint: {'x':0, 'top': 1}
                        canvas.before:
                            Color:
                                rgba: clear_color
                            Rectangle:
                                size: self.size
                                pos: self.pos

                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: 0.05

                    Button:
                        size_hint_x: 0.1
                        text: "Select"
                        disabled: root.loading == True
                        on_press: root.on_select_press()
                    HSpacer:
                        size_hint_x: 0.7
                    ToggleButton:
                        id: mask2
                        size_hint_x: 0.1
                        text: "Mask2"
                        disabled: root.loading == True
                        on_state: root.on_mask2_press(self.state)
                        on_state: geometry.disabled = True if mask2.state == 'down' else False
                    Button:
                        size_hint_x: 0.1
                        text: "Export"
                        disabled: root.loading == True
                        on_press: root.on_export_press()


            TabbedPanel:
                id: effects
                size_hint_x: 0.4
                do_default_tab: False
                tab_width: self.width * 0.12
                tab_height: self.height * 0.05
                disabled: root.loading == True
                on_current_tab: root.on_current_tab(self.current_tab)
                on_current_tab: mask2.disabled = self.current_tab.text == "Ge" or root.loading == True

                IconTabbedPanelItem:
                    text: 'Ba'
                    icon_source: 'assets/Basic.png'

                    MDScrollView:

                        BoxLayout:
                            orientation: "vertical"
                            size_hint_y: None
                            height: self.minimum_height

                            HeadLabel:
                                text: ' White Balance'
 
                            ParamSlider:
                                id: slider_color_temperature
                                text: "Temperature"
                                min: 2000
                                max: 12000
                                value: 5000
                                step: 10
                                on_slider: root.apply_effects_lv(2, 'color_temperature')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'color_temperature')
                                on_after_edit: root.end_history_effect_ctrl(2, 'color_temperature')

                            ParamSlider:
                                id: slider_color_tint
                                text: "Tint"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'color_temperature')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'color_temperature')
                                on_after_edit: root.end_history_effect_ctrl(2, 'color_temperature')

                            VSeparator:
 
                            HeadLabel:
                                text: ' Tone'

                            ParamSlider:
                                id: slider_exposure
                                text: "Exposure"                            
                                min: -4.0
                                max: 4.0
                                value: 0.0
                                step: 0.05
                                for_float: True
                                on_slider: root.apply_effects_lv(2, 'exposure')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'exposure')
                                on_after_edit: root.end_history_effect_ctrl(2, 'exposure')

                            ParamSlider:
                                id: slider_contrast
                                text: "Contrast"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'contrast')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'contrast')
                                on_after_edit: root.end_history_effect_ctrl(2, 'contrast')

                            VSeparator:

                            ParamSlider:
                                id: slider_midtone
                                text: "Midtone"                            
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'tone')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'tone')
                                on_after_edit: root.end_history_effect_ctrl(2, 'tone')

                            ParamSlider:
                                id: slider_highlight
                                text: "Highlights"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'tone')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'tone')
                                on_after_edit: root.end_history_effect_ctrl(2, 'tone')

                            ParamSlider:
                                id: slider_shadow
                                text: "Shadows"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'tone')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'tone')
                                on_after_edit: root.end_history_effect_ctrl(2, 'tone')

                            VSeparator:

                            HeadLabel:
                                text: ' Level'

                            ParamSlider:
                                id: slider_black_level
                                text: "Black Level"
                                min: 0
                                max: 253
                                value: 0
                                for_float: True
                                step: 0.1
                                on_slider: root.apply_effects_lv(2, 'level')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'level')
                                on_after_edit: root.end_history_effect_ctrl(2, 'level')

                            ParamSlider:
                                id: slider_mid_level
                                text: "Mid Level"
                                min: 1
                                max: 254
                                value: 127
                                for_float: True
                                step: 0.1
                                on_slider: root.apply_effects_lv(2, 'level')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'level')
                                on_after_edit: root.end_history_effect_ctrl(2, 'level')

                            ParamSlider:
                                id: slider_white_level
                                text: "White Level"
                                min: 2
                                max: 255
                                value: 255
                                for_float: True
                                step: 0.1
                                on_slider: root.apply_effects_lv(2, 'level')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'level')
                                on_after_edit: root.end_history_effect_ctrl(2, 'level')

                            VSeparator:
                            
                            HeadLabel:
                                text: ' Precence'

                            ParamSlider:
                                id: slider_clarity
                                text: "Clarity"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'clarity')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'clarity')
                                on_after_edit: root.end_history_effect_ctrl(2, 'clarity')

                            ParamSlider:
                                id: slider_texture
                                text: "Texture"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'texture')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'texture')
                                on_after_edit: root.end_history_effect_ctrl(2, 'texture')

                            ParamSlider:
                                id: slider_microcontrast
                                text: "Micro Contrast"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'microcontrast')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'microcontrast')
                                on_after_edit: root.end_history_effect_ctrl(2, 'microcontrast')

                            ParamSlider:
                                id: slider_dehaze
                                text: "Dehaze"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'dehaze')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'dehaze')
                                on_after_edit: root.end_history_effect_ctrl(2, 'dehaze')

                            ParamSlider:
                                id: slider_clahe_intensity
                                text: "CLAHE"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'clahe')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'clahe')
                                on_after_edit: root.end_history_effect_ctrl(2, 'clahe')

                            VSeparator:
                            
                            ParamSlider:
                                text: "Saturation"
                                id: slider_saturation
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'vs_and_saturation')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'vs_and_saturation', 'saturation')
                                on_after_edit: root.end_history_effect_ctrl(2, 'vs_and_saturation', 'saturation')

                            ParamSlider:
                                text: "Vibrance"
                                id: slider_vibrance
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'vs_and_saturation')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'vs_and_saturation', 'saturation')
                                on_after_edit: root.end_history_effect_ctrl(2, 'vs_and_saturation', 'saturation')

                            VSeparator:
                                                        
                            HeadLabel:
                                text: ' Color Mixer'

                            TabbedPanel:
                                size_hint_y: None
                                ref_height: 22*3+20+22+6
                                ref_tab_width: 40
                                ref_tab_height: 25
                                do_default_tab: False

                                IconTabbedPanelItem:
                                    icon_source: 'assets/Red.png'

                                    BoxLayout:
                                        orientation: "vertical"
                                        HeadLabel:
                                            text: ' Red'
                                        ParamSlider:
                                            id: slider_hls_red_hue
                                            text: "Hue"
                                            min: -180
                                            max: 180
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_red')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_red')
                                        ParamSlider:
                                            id: slider_hls_red_lum
                                            text: "Luminance"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_red')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_red')
                                        ParamSlider:
                                            id: slider_hls_red_sat
                                            text: "Saturation"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_red')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_red')
                    
                                IconTabbedPanelItem:
                                    icon_source: 'assets/Orange.png'

                                    BoxLayout:
                                        orientation: "vertical"
                                        HeadLabel:
                                            text: ' Orange'
                                        ParamSlider:
                                            id: slider_hls_orange_hue
                                            text: "Hue"
                                            min: -180
                                            max: 180
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_orange')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_orange')
                                        ParamSlider:
                                            id: slider_hls_orange_lum
                                            text: "Luminance"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_orange')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_orange')
                                        ParamSlider:
                                            id: slider_hls_orange_sat
                                            text: "Saturation"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_orange')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_orange')

                                IconTabbedPanelItem:
                                    icon_source: 'assets/Yellow.png'

                                    BoxLayout:
                                        orientation: "vertical"
                                        HeadLabel:
                                            text: ' Yellow'
                                        ParamSlider:
                                            id: slider_hls_yellow_hue
                                            text: "hue"
                                            min: -180
                                            max: 180
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_yellow')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_yellow')
                                        ParamSlider:
                                            id: slider_hls_yellow_lum
                                            text: "Luminance"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_yellow')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_yellow')
                                        ParamSlider:
                                            id: slider_hls_yellow_sat
                                            text: "Saturation"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_yellow')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_yellow')

                                IconTabbedPanelItem:
                                    icon_source: 'assets/Green.png'

                                    BoxLayout:
                                        orientation: "vertical"
                                        HeadLabel:
                                            text: ' Green'
                                        ParamSlider:
                                            id: slider_hls_green_hue
                                            text: "Hue"
                                            min: -180
                                            max: 180
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_green')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_green')
                                        ParamSlider:
                                            id: slider_hls_green_lum
                                            text: "Luminance"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_green')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_green')
                                        ParamSlider:
                                            id: slider_hls_green_sat
                                            text: "Saturation"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_green')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_green')

                                IconTabbedPanelItem:
                                    icon_source: 'assets/Cyan.png'

                                    BoxLayout:
                                        orientation: "vertical"
                                        HeadLabel:
                                            text: ' Cyan'
                                        ParamSlider:
                                            id: slider_hls_cyan_hue
                                            text: "Hue"
                                            min: -180
                                            max: 180
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_cyan')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_cyan')
                                        ParamSlider:
                                            id: slider_hls_cyan_lum
                                            text: "Luminance"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_cyan')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_cyan')
                                        ParamSlider:
                                            id: slider_hls_cyan_sat
                                            text: "Saturation"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_cyan')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_cyan')

                                IconTabbedPanelItem:
                                    icon_source: 'assets/Blue.png'

                                    BoxLayout:
                                        orientation: "vertical"
                                        HeadLabel:
                                            text: ' Blue'
                                        ParamSlider:
                                            id: slider_hls_blue_hue
                                            text: "Hue"
                                            min: -180
                                            max: 180
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_blue')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_blue')
                                        ParamSlider:
                                            id: slider_hls_blue_lum
                                            text: "Luminance"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_blue')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_blue')
                                        ParamSlider:
                                            id: slider_hls_blue_sat
                                            text: "Saturation"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_blue')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_blue')

                                IconTabbedPanelItem:
                                    icon_source: 'assets/Purple.png'

                                    BoxLayout:
                                        orientation: "vertical"
                                        HeadLabel:
                                            text: ' Purple'
                                        ParamSlider:
                                            id: slider_hls_purple_hue
                                            text: "Hue"
                                            min: -180
                                            max: 180
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_purple')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_purple')
                                        ParamSlider:
                                            id: slider_hls_purple_lum
                                            text: "Luminance"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_purple')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_purple')
                                        ParamSlider:
                                            id: slider_hls_purple_sat
                                            text: "Saturation"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_purple')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_purple')

                                IconTabbedPanelItem:
                                    icon_source: 'assets/Magenta.png'

                                    BoxLayout:
                                        orientation: "vertical"
                                        HeadLabel:
                                            text: ' Magenta'
                                        ParamSlider:
                                            id: slider_hls_magenta_hue
                                            text: "Hue"
                                            min: -180
                                            max: 180
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_magenta')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_magenta')
                                        ParamSlider:
                                            id: slider_hls_magenta_lum
                                            text: "Luminance"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_magenta')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_magenta')
                                        ParamSlider:
                                            id: slider_hls_magenta_sat
                                            text: "Saturation"
                                            min: -100
                                            max: 100
                                            value: 0
                                            step: 1
                                            on_slider: root.apply_effects_lv(2, 'hls')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'hls', 'hls_magenta')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'hls', 'hls_magenta')

                            VSeparator:
 
                            HeadLabel:
                                text: ' Unsharp mask'

                            ParamSlider:
                                id: slider_unsharp_mask_amount
                                text: "Amount"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'unsharp_mask')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'unsharp_mask')
                                on_after_edit: root.end_history_effect_ctrl(2, 'unsharp_mask')

                            ParamSlider:
                                id: slider_unsharp_mask_sigma
                                text: "Sigma"
                                min: 0
                                max: 100
                                value: 50
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'unsharp_mask')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'unsharp_mask')
                                on_after_edit: root.end_history_effect_ctrl(2, 'unsharp_mask')

                            VSeparator:
 
                            HeadLabel:
                                text: ' Vignette'

                            ParamSlider:
                                id: slider_vignette_intensity
                                text: "Intensity"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(4, 'vignette')
                                on_before_edit: root.begin_history_effect_ctrl(4, 'vignette')
                                on_after_edit: root.end_history_effect_ctrl(4, 'vignette')

                            ParamSlider:
                                id: slider_vignette_radius_percent
                                text: "Radius"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(4, 'vignette')
                                on_before_edit: root.begin_history_effect_ctrl(4, 'vignette')
                                on_after_edit: root.end_history_effect_ctrl(4, 'vignette')

                            ParamSlider:
                                id: slider_vignette_softness
                                text: "Softness"
                                min: 0
                                max: 100
                                value: 100
                                step: 1
                                on_slider: root.apply_effects_lv(4, 'vignette')
                                on_before_edit: root.begin_history_effect_ctrl(4, 'vignette')
                                on_after_edit: root.end_history_effect_ctrl(4, 'vignette')
                            
                            VSeparator:

                            HeadLabel:
                                text: ' Lens Modifier'

                            MDGridLayout:
                                size_hint_y: None
                                ref_height: 40
                                ref_width: 120
                                cols: 6

                                ParamLabel:          
                                    text: "Color"
                                CheckBox:
                                    id: checkbox_color_modification
                                    active: True
                                    on_press: root.apply_effects_lv(0, 'lens_modifier')
                                    on_touch_down: if self.collide_point(*args[1].pos): root.begin_history_effect_ctrl(0, 'lens_modifier')
                                    on_touch_up: root.end_history_effect_ctrl(0, 'lens_modifier')
                                ParamLabel:          
                                    text: "Subpixel"
                                CheckBox:
                                    id: checkbox_subpixel_distortion
                                    active: True
                                    on_press: root.apply_effects_lv(0, 'lens_modifier')
                                    on_touch_down: if self.collide_point(*args[1].pos): root.begin_history_effect_ctrl(0, 'lens_modifier')
                                    on_touch_up: root.end_history_effect_ctrl(0, 'lens_modifier')
                                ParamLabel:          
                                    text: "Geometry"
                                CheckBox:
                                    id: checkbox_geometry_distortion
                                    active: True
                                    on_press: root.apply_effects_lv(0, 'lens_modifier')
                                    on_touch_down: if self.collide_point(*args[1].pos): root.begin_history_effect_ctrl(0, 'lens_modifier')
                                    on_touch_up: root.end_history_effect_ctrl(0, 'lens_modifier')

                            VSpacer

                IconTabbedPanelItem:
                    text: 'Cu'
                    icon_source: 'assets/Curves.png'

                    MDScrollView:

                        BoxLayout:
                            orientation: "vertical"
                            size_hint_y: None
                            height: self.minimum_height

                            HeadLabel:
                                text: ' Tone Curve'

                            CurveTabbedPanel:
                                default_tab: tab_all

                                TabbedPanelItem:
                                    id: tab_all
                                    text: 'All'

                                    CurveWidget:
                                        id: tonecurve
                                        start_y: 0.0
                                        end_y: 1.0
                                        on_curve: root.apply_effects_lv(2, 'curve')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'curve', 'tonecurve')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'curve', 'tonecurve')

                                TabbedPanelItem:
                                    text: 'Red'

                                    CurveWidget:
                                        id: tonecurve_red
                                        start_y: 0.0
                                        end_y: 1.0
                                        on_curve: root.apply_effects_lv(2, 'curve')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'curve', 'tonecurve_red')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'curve', 'tonecurve_red')

                                TabbedPanelItem:
                                    text: 'Green'

                                    CurveWidget:
                                        id: tonecurve_green
                                        start_y: 0.0
                                        end_y: 1.0
                                        on_curve: root.apply_effects_lv(2, 'curve')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'curve', 'tonecurve_green')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'curve', 'tonecurve_green')

                                TabbedPanelItem:
                                    text: 'Blue'

                                    CurveWidget:
                                        id: tonecurve_blue
                                        start_y: 0.0
                                        end_y: 1.0
                                        on_curve: root.apply_effects_lv(2, 'curve')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'curve', 'tonecurve_blue')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'curve', 'tonecurve_blue')
                                
                            VSpacer:
                            
                            HeadLabel:
                                text: ' Color Grading'

                            CurveTabbedPanel:
                                ref_tab_width: 100
                                default_tab: tab_grading1

                                TabbedPanelItem:
                                    id: tab_grading1
                                    text: 'Grading 1'

                                    BoxLayout:
                                        orientation: "vertical"
                                        #size_hint_y: None
                                        #height: self.minimum_height
                                        
                                        CurveWidget:
                                            id: grading1
                                            start_y: 1.0
                                            end_y: 0.0
                                            on_curve: root.apply_effects_lv(2, 'curve')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'curve', 'grading1')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'curve', 'grading1')

                                        CWColorPicker:
                                            id: grading1_color_picker
                                            on_current_color: root.apply_effects_lv(2, 'curve')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'curve', 'grading1')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'curve', 'grading1')


                                TabbedPanelItem:
                                    text: 'Grading 2'

                                    BoxLayout:
                                        orientation: "vertical"
                                        #size_hint_y: None
                                        #height: self.minimum_height

                                        CurveWidget:
                                            id: grading2
                                            start_y: 0.0
                                            end_y: 1.0
                                            on_curve: root.apply_effects_lv(2, 'curve')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'curve', 'grading2')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'curve', 'grading2')

                                        CWColorPicker:
                                            id: grading2_color_picker
                                            on_current_color: root.apply_effects_lv(2, 'curve')
                                            on_before_edit: root.begin_history_effect_ctrl(2, 'curve', 'grading2')
                                            on_after_edit: root.end_history_effect_ctrl(2, 'curve', 'grading2')
                            
                            VSpacer:
                                ref_height: 4

                            HeadLabel:
                                text: ' Color Curves'
                            
                            CurveTabbedPanel:
                                ref_tab_width: 100
                                default_tab: tab_lum_vs_lum

                                TabbedPanelItem:
                                    text: 'Hue vs Hue'

                                    HeadLabel:
                                        text: "Hue vs Hue"
                                    CurveWidget:
                                        id: HuevsHue
                                        start_y: 0.5
                                        end_y: 0.5
                                        on_curve: root.apply_effects_lv(2, 'vs_and_saturation')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'vs_and_saturation', 'HuevsHue')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'vs_and_saturation', 'HuevsHue')

                                TabbedPanelItem:
                                    text: 'Hue vs Lum'

                                    HeadLabel:
                                        text: "Hue vs Lum"
                                    CurveWidget:
                                        id: HuevsLum
                                        start_y: 0.5
                                        end_y: 0.5
                                        on_curve: root.apply_effects_lv(2, 'vs_and_saturation')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'vs_and_saturation', 'HuevsLum')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'vs_and_saturation', 'HuevsLum')

                                TabbedPanelItem:
                                    text: 'Hue vs Sat'

                                    HeadLabel:
                                        text: "Hue vs Sat"
                                    CurveWidget:
                                        id: HuevsSat
                                        start_y: 0.5
                                        end_y: 0.5
                                        on_curve: root.apply_effects_lv(2, 'vs_and_saturation')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'vs_and_saturation', 'HuevsSat')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'vs_and_saturation', 'HuevsSat')

                                TabbedPanelItem:
                                    id: tab_lum_vs_lum
                                    text: 'Lum vs Lum'

                                    HeadLabel:
                                        text: "Lum vs Lum"
                                    CurveWidget:
                                        id: LumvsLum
                                        start_y: 0.5
                                        end_y: 0.5
                                        on_curve: root.apply_effects_lv(2, 'vs_and_saturation')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'vs_and_saturation', 'LumvsLum')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'vs_and_saturation', 'LumvsLum')

                                TabbedPanelItem:
                                    text: 'Lum vs Sat'

                                    HeadLabel:
                                        text: "Lum vs Sat"
                                    CurveWidget:
                                        id: LumvsSat
                                        start_y: 0.5
                                        end_y: 0.5
                                        on_curve: root.apply_effects_lv(2, 'vs_and_saturation')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'vs_and_saturation', 'LumvsSat')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'vs_and_saturation', 'LumvsSat')

                                TabbedPanelItem:
                                    text: 'Sat vs Lum'

                                    HeadLabel:
                                        text: "Sat vs Lum"
                                    CurveWidget:
                                        id: SatvsLum
                                        start_y: 0.5
                                        end_y: 0.5
                                        on_curve: root.apply_effects_lv(2, 'vs_and_saturation')                            
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'vs_and_saturation', 'SatvsLum')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'vs_and_saturation', 'SatvsLum')

                                TabbedPanelItem:
                                    text: 'Sat vs Sat'

                                    HeadLabel:
                                        text: "Sat vs Sat"
                                    CurveWidget:
                                        id: SatvsSat
                                        start_y: 0.5
                                        end_y: 0.5
                                        on_curve: root.apply_effects_lv(2, 'vs_and_saturation')
                                        on_before_edit: root.begin_history_effect_ctrl(2, 'vs_and_saturation', 'SatvsSat')
                                        on_after_edit: root.end_history_effect_ctrl(2, 'vs_and_saturation', 'SatvsSat')

                                VSpacer:

                IconTabbedPanelItem:
                    text: 'Ex'
                    icon_source: 'assets/Extra.png'

                    MDScrollView:

                        MDBoxLayout:
                            orientation: "vertical"
                            size_hint_y: None
                            height: self.minimum_height

                            HeadLabel:
                                text: ' Noise Reduction'

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "AI"
                                VSpacer:
                                    size_hint_x: 0.55
                                ParamChip:
                                    id: switch_ai_noise_reduction
                                    size_hint_x: None
                                    ref_width: 40
                                    on_active: root.begin_history_effect_ctrl(0, 'ai_noise_reduction')
                                    on_active: root.apply_effects_lv(0, 'ai_noise_reduction')
                                    on_release: root.end_history_effect_ctrl(0, 'ai_noise_reduction')
                                    ParamChipText:
                                        text: "AI"

                            ParamSlider:
                                id: slider_light_noise_reduction
                                text: "Luminace"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'light_noise_reduction')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'light_noise_reduction')
                                on_after_edit: root.end_history_effect_ctrl(2, 'light_noise_reduction')

                            ParamSlider:
                                id: slider_light_color_noise_reduction
                                text: "Color"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'light_noise_reduction')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'light_noise_reduction')
                                on_after_edit: root.end_history_effect_ctrl(2, 'light_noise_reduction')

                            VSeparator:

                            HeadLabel:
                                text: ' Details'

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Inpaint"
                                VSpacer:
                                    size_hint_x: 0.25
                                ParamChip:
                                    id: switch_inpaint
                                    size_hint_x: None
                                    ref_width: 60
                                    on_active: root.begin_history_effect_ctrl(0, 'inpaint')
                                    on_active: root.apply_effects_lv(0, 'inpaint')
                                    on_release: root.end_history_effect_ctrl(0, 'inpaint')
                                    ParamChipText:
                                        text: "Mask"
                                ParamChip:
                                    type: 'assist'
                                    id: button_inpaint_predict
                                    size_hint_x: None
                                    ref_width: 60
                                    on_press: root.begin_history_effect_ctrl(0, 'inpaint')
                                    on_press: root.apply_effects_lv(0, 'inpaint')
                                    on_release: root._set_diff_list_to_inpaint_edit()
                                    on_release: root.end_history_effect_ctrl(0, 'inpaint')
                                    ParamChipText:
                                        text: "Erase"
                                ToggleButton:
                                    id: toggle_inpaint_edit
                                    size_hint_x: None
                                    ref_width: 40
                                    text: "Edit"
                                    on_state: root.on_inpaint_edit_press(self.state)
                                    #on_state: geometry.disabled = True if mask2.state == 'down' else False

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Defocus"
                                VSpacer:
                                    size_hint_x: 0.55
                                ParamChip:
                                    id: switch_defocus
                                    size_hint_x: None
                                    ref_width: 40
                                    on_active: root.begin_history_effect_ctrl(1, 'defocus')
                                    on_active: root.apply_effects_lv(1, 'defocus')
                                    on_release: root.end_history_effect_ctrl(1, 'defocus')
                                    ParamChipText:
                                        text: "AI"

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Subpixel shift"
                                VSpacer:
                                    size_hint_x: 0.55
                                ParamChip:
                                    id: switch_subpixel_shift
                                    size_hint_x: None
                                    ref_width: 40
                                    on_active: root.begin_history_effect_ctrl(0, 'subpixel_shift')
                                    on_active: root.apply_effects_lv(0, 'subpixel_shift')
                                    on_release: root.end_history_effect_ctrl(0, 'subpixel_shift')
                                    ParamChipText:
                                        text: "AI"

                            ParamSlider:
                                id: slider_deblur_filter
                                text: "Deblur"
                                min: 0
                                max: 50
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(1, 'deblur_filter')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'deblur_filter')
                                on_after_edit: root.end_history_effect_ctrl(1, 'deblur_filter')
                                
                            VSeparator:

                            HeadLabel:
                                text: ' LUT'

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "File"
                                VSpacer:
                                    size_hint_x: 0.12
                                ParamSpinner:
                                    id: lut_spinner
                                    values: [ 'None', ]
                                    #on_hovered_item: root.apply_effects_lv(2, 'lut')
                                    on_touch_down: if self.collide_point(*args[1].pos): root.begin_history_effect_ctrl(2, 'lut')
                                    on_text: root.apply_effects_lv(2, 'lut')
                                    on_text: root.end_history_effect_ctrl(2, 'lut')
                                Button:
                                    pos_hint: {'center_x': .5, 'center_y': .5}
                                    size_hint: 0.08, None
                                    ref_height: 20
                                    on_press: root.on_lut_select_folder()

                            ParamSlider:
                                id: slider_lut_intensity
                                text: "Intensity"
                                min: 0
                                max: 100
                                value: 100
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'lut')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'lut')
                                on_after_edit: root.end_history_effect_ctrl(2, 'lut')

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "to Log option"
                                VSpacer:
                                    size_hint_x: 0.1
                                ParamSpinner:
                                    id: lut_to_log_spinner
                                    values: [ 'None', 'slog3', 'logc4', 'clog3', 'redlog3g10', 'vlog', 'nlog', 'flog2', 'omlog400' ]
                                    on_touch_down: if self.collide_point(*args[1].pos): root.begin_history_effect_ctrl(2, 'lut')
                                    on_text: root.apply_effects_lv(2, 'lut')
                                    on_text: root.end_history_effect_ctrl(2, 'lut')

                            VSeparator:

                            HeadLabel:
                                text: ' Film Simulation'

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Type"
                                VSpacer:
                                    size_hint_x: 0.1
                                ParamSpinner:
                                    id: spinner_film_preset
                                    values: [ 'None', ]
                                    on_hovered_item: root.apply_effects_lv(2, 'film_emulation')
                                    on_touch_down: if self.collide_point(*args[1].pos): root.begin_history_effect_ctrl(2, 'film_emulation')
                                    on_text:  root.end_history_effect_ctrl(2, 'film_emulation')
                                    
                            ParamSlider:
                                id: slider_film_intensity
                                text: "Intensity"
                                min: 0
                                max: 100
                                value: 100
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'film_emulation')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'film_emulation')
                                on_after_edit: root.end_history_effect_ctrl(2, 'film_emulation')

                            ParamSlider:
                                id: slider_film_expired
                                text: "Expired"
                                min: 0
                                max: 100
                                value: 100
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'film_emulation')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'film_emulation')
                                on_after_edit: root.end_history_effect_ctrl(2, 'film_emulation')

                            HeadLabel:
                                text: ' Lens Simulator'

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Type"
                                VSpacer:
                                    size_hint_x: 0.1
                                ParamSpinner:
                                    id: spinner_lens_preset
                                    values: [ 'None', ]
                                    on_hovered_item: root.apply_effects_lv(2, 'lens_simulator')
                                    on_touch_down: if self.collide_point(*args[1].pos): root.begin_history_effect_ctrl(2, 'lens_simulator')
                                    on_text:  root.end_history_effect_ctrl(2, 'lens_simulator')
                                    
                            ParamSlider:
                                id: slider_lens_intensity
                                text: "Intensity"
                                min: 0
                                max: 100
                                value: 100
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'lens_simulator')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'lens_simulator')
                                on_after_edit: root.end_history_effect_ctrl(2, 'lens_simulator')

                            VSeparator:

                            HeadLabel:
                                text: ' Filter'

                            ParamSlider:
                                id: slider_lensblur_filter
                                text: "Lensblur"
                                min: 0
                                max: 100
                                value: 0
                                step: 2
                                on_slider: root.apply_effects_lv(1, 'lensblur_filter')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'lensblur_filter')
                                on_after_edit: root.end_history_effect_ctrl(1, 'lensblur_filter')

                            ParamSlider:
                                id: slider_scratch
                                text: "Scratch"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(1, 'scratch')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'scratch')
                                on_after_edit: root.end_history_effect_ctrl(1, 'scratch')

                            ParamSlider:
                                id: slider_frosted_glass
                                text: "Frosted Glass"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(1, 'frosted_glass')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'frosted_glass')
                                on_after_edit: root.end_history_effect_ctrl(1, 'frosted_glass')

                            ParamSlider:
                                id: slider_mosaic
                                text: "Mosaic"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(1, 'mosaic')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'mosaic')
                                on_after_edit: root.end_history_effect_ctrl(1, 'mosaic')

                            VSeparator:

                            HeadLabel:
                                text: ' Glow Effect'

                            ParamSlider:
                                id: slider_glow_black
                                text: "Black"
                                min: 0
                                max: 126
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'glow')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'glow')
                                on_after_edit: root.end_history_effect_ctrl(2, 'glow')

                            ParamSlider:
                                id: slider_glow_gauss
                                text: "Gauss"
                                min: 0
                                max: 100
                                value: 0
                                step: 2
                                on_slider: root.apply_effects_lv(2, 'glow')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'glow')
                                on_after_edit: root.end_history_effect_ctrl(2, 'glow')

                            ParamSlider:
                                id: slider_glow_opacity
                                text: "Opacity"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'glow')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'glow')
                                on_after_edit: root.end_history_effect_ctrl(2, 'glow')

                            VSeparator:
 
                            HeadLabel:
                                text: ' Grain'

                            ParamSlider:
                                id: slider_grain_intensity
                                text: "Intensity"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(4, 'grain')
                                on_before_edit: root.begin_history_effect_ctrl(4, 'grain')
                                on_after_edit: root.end_history_effect_ctrl(4, 'grain')
                            ParamSlider:
                                id: slider_grain_size
                                text: "Size"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(4, 'grain')
                                on_before_edit: root.begin_history_effect_ctrl(4, 'grain')
                                on_after_edit: root.end_history_effect_ctrl(4, 'grain')
                            ParamSlider:
                                id: slider_grain_blue_bias
                                text: "Blue bias"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(4, 'grain')
                                on_before_edit: root.begin_history_effect_ctrl(4, 'grain')
                                on_after_edit: root.end_history_effect_ctrl(4, 'grain')
                            ParamSlider:
                                id: slider_grain_shadow_boost
                                text: "Shadow boost"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(4, 'grain')
                                on_before_edit: root.begin_history_effect_ctrl(4, 'grain')
                                on_after_edit: root.end_history_effect_ctrl(4, 'grain')
                            ParamSlider:
                                id: slider_grain_color_noise_ratio
                                text: "Color noise"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(4, 'grain')
                                on_before_edit: root.begin_history_effect_ctrl(4, 'grain')
                                on_after_edit: root.end_history_effect_ctrl(4, 'grain')

                            VSeparator:
 
                            HeadLabel:
                                text: ' Solid Color'

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Solid Color"
                                VSpacer:
                                    size_hint_x: 0.45
                                ParamChip:
                                    id: switch_solid_color
                                    size_hint_x: None
                                    ref_width: 60
                                    on_active: root.begin_history_effect_ctrl(2, 'solid_color')
                                    on_active: root.apply_effects_lv(2, 'solid_color')
                                    on_release: root.end_history_effect_ctrl(2, 'solid_color')
                                    ParamChipText:
                                        text: "Apply"
                            ParamSlider:
                                id: slider_solid_color
                                text: "Opacity"
                                min: 0
                                max: 100
                                value: 50
                                step: 1
                                on_slider: root.apply_effects_lv(2, 'solid_color')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'solid_color')
                                on_after_edit: root.end_history_effect_ctrl(2, 'solid_color')

                            VSpacer:
                                ref_height: 4

                            CWColorPicker:
                                id: cp_solid_color
                                on_current_color: root.apply_effects_lv(2, 'solid_color')
                                on_before_edit: root.begin_history_effect_ctrl(2, 'solid_color')
                                on_after_edit: root.end_history_effect_ctrl(2, 'solid_color')

                            VSeparator:
 
                            HeadLabel:
                                text: ' Exception'

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Tonemap"
                                VSpacer:
                                    size_hint_x: 0.45
                                ParamChip:
                                    id: switch_highlight_compress
                                    size_hint_x: None
                                    ref_width: 60
                                    active: False
                                    on_active: root.begin_history_effect_ctrl(2, 'highlight_compress')
                                    on_active: root.apply_effects_lv(2, 'highlight_compress')
                                    on_release: root.end_history_effect_ctrl(2, 'highlight_compress')
                                    ParamChipText:
                                        text: "Apply"
                            
                            VSpacer:

                IconTabbedPanelItem:
                    id: geometry
                    icon_source: 'assets/Geometry.png'
                    text: 'Ge'

                    MDScrollView:

                        MDBoxLayout:
                            orientation: "vertical"
                            size_hint_y: None
                            height: self.minimum_height

                            HeadLabel:
                                text: ' Rotation'

                            ParamSlider:
                                id: slider_rotation
                                text: "Angle"
                                min: -45.0
                                max: 45.0
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(0, 'rotation')
                                on_slider: root.apply_effects_lv(0, 'crop')
                                on_before_edit: root.begin_history_effect_ctrl(0, 'rotation')
                                on_after_edit: root.end_history_effect_ctrl(0, 'rotation')

                            VSpacer:
                            
                            ParamBoxLayout:

                                HSpacer:
                                    ref_width: 100
                                Button:
                                    pos_hint: {'center_x': .5, 'center_y': .5}
                                    ref_height: 20
                                    text: "L"
                                    on_press: root.apply_effects_lv(0, 'crop')
                                    on_press: root.set_effect_param(0, 'rotation', 90)
                                Button:
                                    pos_hint: {'center_x': .5, 'center_y': .5}
                                    ref_height: 20
                                    text: "R"
                                    on_press: root.apply_effects_lv(0, 'crop')
                                    on_press: root.set_effect_param(0, 'rotation', -90)
                                Button:
                                    pos_hint: {'center_x': .5, 'center_y': .5}
                                    ref_height: 20
                                    text: "H"
                                    on_press: root.apply_effects_lv(0, 'crop')
                                    on_press: root.set_effect_param(0, 'rotation', 'hflip')
                                Button:
                                    pos_hint: {'center_x': .5, 'center_y': .5}
                                    ref_height: 20
                                    text: "V"
                                    on_press: root.apply_effects_lv(0, 'crop')
                                    on_press: root.set_effect_param(0, 'rotation', 'vflip')

                            VSeparator:

                            HeadLabel:
                                text: " Crop"

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Crop"
                                HSpacer:
                                    size_hint_x: 0.5
                                ParamChip:
                                    type: 'assist'
                                    id: button_crop_reset
                                    size_hint_x: None
                                    ref_width: 60
                                    on_press: root.begin_history_effect_ctrl(0, 'crop')
                                    on_press: root.apply_effects_lv(0, 'crop')
                                    on_release: root.end_history_effect_ctrl(0, 'crop')
                                    ParamChipText:
                                        text: "Reset"
                                    
                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Aspect Ratio"
                                HSpacer:
                                    size_hint_x: 0.15
                                ParamSpinner:
                                    id: spinner_acpect_ratio
                                    values: ["None", "1 / 1", "5 / 4", "3 / 2", "4 / 3", "16 / 9", "1.414 / 1", "148 / 100"]
                                    on_text: root.apply_effects_lv(0, 'crop')

                IconTabbedPanelItem:
                    text: 'Lo'
                    icon_source: 'assets/Looks.png'

                    MDScrollView:

                        MDBoxLayout:
                            orientation: "vertical"
                            size_hint_y: None
                            height: self.minimum_height

                            HeadLabel:
                                text: ' Face'
                            ParamSlider:
                                id: slider_jawline_scale
                                text: "Jawline"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(1, 'face')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'face')
                                on_after_edit: root.end_history_effect_ctrl(1, 'face')
                            ParamSlider:
                                id: slider_jaw_scale
                                text: "Jaw"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(1, 'face')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'face')
                                on_after_edit: root.end_history_effect_ctrl(1, 'face')

                            ParamSlider:
                                id: slider_left_eye_scale
                                text: "Left eye"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(1, 'face')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'face')
                                on_after_edit: root.end_history_effect_ctrl(1, 'face')
                            ParamSlider:
                                id: slider_right_eye_scale
                                text: "Right eye"
                                min: 0
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(1, 'face')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'face')
                                on_after_edit: root.end_history_effect_ctrl(1, 'face')

                            ParamSlider:
                                id: slider_lips_scale
                                text: "Lips"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(1, 'face')
                                on_before_edit: root.begin_history_effect_ctrl(1, 'face')
                                on_after_edit: root.end_history_effect_ctrl(1, 'face')

                IconTabbedPanelItem:
                    text: 'M2'
                    icon_source: 'assets/Mask2.png'

                    MDScrollView:

                        MDBoxLayout:
                            id: mask2_panel
                            orientation: "vertical"
                            size_hint_y: None
                            height: self.minimum_height

                            HeadLabel:
                                text: ' Settings'

                            MDGridLayout:
                                size_hint_y: None
                                ref_height: 20
                                cols: 6

                                ParamLabel:          
                                    text: "Invert"
                                CheckBox:
                                    id: checkbox_mask2_invert
                                    active: False
                                    on_press: root.apply_effects_lv(3, 'mask2')
                                ParamLabel:           
                                    text: " "
                                Label:          
                                    text: " "
                                ParamLabel:           
                                    text: " "
                                Label:          
                                    text: " "

                            VSeparator:

                            HeadLabel:
                                text: ' Depth'
                            ParamSlider:
                                id: slider_mask2_depth_min
                                text: "Min"
                                min: 0
                                max: 255
                                value: 0
                                step: 0.1
                                for_float: True
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')
                            ParamSlider:
                                id: slider_mask2_depth_max
                                text: "Max"
                                min: 0
                                max: 255
                                value: 255
                                step: 0.1
                                for_float: True
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')

                            HeadLabel:
                                text: ' Hue'
                            ParamSlider:
                                id: slider_mask2_hue_distance
                                text: "Distance"
                                min: 0
                                max: 179
                                value: 179
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')
                            ParamSlider:
                                id: slider_mask2_hue_min
                                text: "Min"
                                min: 0
                                max: 359
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')
                            ParamSlider:
                                id: slider_mask2_hue_max
                                text: "Max"
                                min: 0
                                max: 359
                                value: 359
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')

                            HeadLabel:
                                text: ' Lum'
                            ParamSlider:
                                id: slider_mask2_lum_distance
                                text: "Distance"
                                min: 0
                                max: 127
                                value: 127
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')
                            ParamSlider:
                                id: slider_mask2_lum_min
                                text: "Min"
                                min: 0
                                max: 255
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')
                            ParamSlider:
                                id: slider_mask2_lum_max
                                text: "Max"
                                min: 0
                                max: 255
                                value: 255
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')

                            HeadLabel:
                                text: ' Sat'
                            ParamSlider:
                                id: slider_mask2_sat_distance
                                text: "Distance"
                                min: 0
                                max: 127
                                value: 127
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')
                            ParamSlider:
                                id: slider_mask2_sat_min
                                text: "Min"
                                min: 0
                                max: 255
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')
                            ParamSlider:
                                id: slider_mask2_sat_max
                                text: "Max"
                                min: 0
                                max: 255
                                value: 255
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')

                            VSeparator:

                            ParamSlider:
                                id: slider_mask2_blur
                                text: "Blur"
                                min: 0
                                max: 100
                                value: 0
                                step: 2
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')

                            ParamSlider:
                                id: slider_mask2_open_space
                                text: "Open space"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')

                            ParamSlider:
                                id: slider_mask2_close_space
                                text: "Close space"
                                min: -100
                                max: 100
                                value: 0
                                step: 1
                                on_slider: root.apply_effects_lv(3, 'mask2')
                                on_before_edit: root.begin_history_effect_ctrl(3, 'mask2')
                                on_after_edit: root.end_history_effect_ctrl(3, 'mask2')

                            VSeparator:

                            HeadLabel:
                                text: ' Face'

                            MDGridLayout:
                                id: grid_mask2_face
                                size_hint_y: None
                                ref_height: 40
                                ref_width: 120
                                cols: 6

                                ParamLabel:          
                                    text: "Face"
                                CheckBox:
                                    id: checkbox_mask2_face_face
                                    active: True
                                    on_press: root.apply_effects_lv(3, 'mask2')
                                ParamLabel:          
                                    text: "Brows"
                                CheckBox:
                                    id: checkbox_mask2_face_brows
                                    active: True
                                    on_press: root.apply_effects_lv(3, 'mask2')
                                ParamLabel:          
                                    text: "Eyes"
                                CheckBox:
                                    id: checkbox_mask2_face_eyes
                                    active: True
                                    on_press: root.apply_effects_lv(3, 'mask2')
                                ParamLabel:          
                                    text: "Nose"
                                CheckBox:
                                    id: checkbox_mask2_face_nose
                                    active: True
                                    on_press: root.apply_effects_lv(3, 'mask2')
                                ParamLabel:          
                                    text: "Mouth"
                                CheckBox:
                                    id: checkbox_mask2_face_mouth
                                    active: True
                                    on_press: root.apply_effects_lv(3, 'mask2')
                                ParamLabel:          
                                    text: "Lips"
                                CheckBox:
                                    id: checkbox_mask2_face_lips
                                    active: True
                                    on_press: root.apply_effects_lv(3, 'mask2')

                IconTabbedPanelItem:
                    text: 'Li'
                    icon_source: 'assets/Liquify.png'

                    MDScrollView:

                        MDBoxLayout:
                            orientation: "vertical"
                            size_hint_y: None
                            height: self.minimum_height

                            HeadLabel:
                                text: ' Distortion'

                            VSpacer:

                            ParamBoxLayout:

                                HSpacer:
                                    ref_width: 100

                                DistortionEffectButton:
                                    text: "For. Warp"
                                    state: 'down'
                                    on_press: root.set_effect_param(0, 'distortion', 'forward_warp')
                                
                                DistortionEffectButton:
                                    text: "Bulge"
                                    on_press: root.set_effect_param(0, 'distortion', 'bulge')
                                
                                DistortionEffectButton:
                                    text: "Pinch"
                                    on_press: root.set_effect_param(0, 'distortion', 'pinch')
                                
                                DistortionEffectButton:
                                    text: "Swirl"
                                    on_press: root.set_effect_param(0, 'distortion', 'swirl')

                                DistortionEffectButton:
                                    text: "Restore"
                                    on_press: root.set_effect_param(0, 'distortion', 'restore')

                            VSpacer:

                            ParamSlider:
                                id: slider_distortion_brush_size
                                text: "Brush Size"
                                min: 10
                                max: 300
                                value: 100
                                step: 1
                                on_slider: root.apply_effects_lv(0, 'distortion')
                                on_before_edit: root.begin_history_effect_ctrl(0, 'distortion')
                                on_after_edit: root.end_history_effect_ctrl(0, 'distortion')
                            ParamSlider:
                                id: slider_distortion_strength
                                text: "Strength"
                                min: 1
                                max: 100
                                value: 50
                                step: 1
                                on_slider: root.apply_effects_lv(0, 'distortion')
                                on_before_edit: root.begin_history_effect_ctrl(0, 'distortion')
                                on_after_edit: root.end_history_effect_ctrl(0, 'distortion')

                            ParamBoxLayout:
                                ParamLabel:
                                    text: "Paint"
                                HSpacer:
                                    size_hint_x: 0.5
                                ParamChip:
                                    type: 'assist'
                                    id: button_distortion_reset
                                    size_hint_x: None
                                    ref_width: 60
                                    on_press: root.begin_history_effect_ctrl(0, 'distortion')
                                    on_press: root.apply_effects_lv(0, 'distortion')
                                    on_release: root.end_history_effect_ctrl(0, 'distortion')
                                    ParamChipText:
                                        text: "Reset"

        ViewerWidget:
            id: viewer
            size_hint_y: None
            ref_height: 160
            grid_width: 100
            on_last_selected: root.on_select(self.last_selected)

